- name: Create Shibboleth SP keys
  shell: /usr/sbin/shib-keygen -h sp.example.org -e https://sp.example.org/shibboleth 
  args:
    creates: /etc/shibboleth/sp-key.pem

- name: Create metadata directory for IdP metadata
  file: name=/etc/shibboleth/metadata state=directory

- name: Configure Shibboleth SP
  copy:
    src: roles/mod-shib2/files/shibboleth2.xml
    dest: /etc/shibboleth/shibboleth2.xml
    
- name: Configure Shibboleth SP Attribute Map
  copy:
    src: roles/mod-shib2/files/attribute-map.xml
    dest: /etc/shibboleth/attribute-map.xml

- name: Add IdP Metadata to Shibboleth SP
  get_url:
    url: https://idp.example.org/idp/shibboleth
    dest: /etc/shibboleth/metadata/idp.example.org-metadata.xml
    validate_certs: no
  when: pre_t is defined and pre_t > 2
  
- name: Restart shibd
  service: name=shibd state=restarted enabled=yes
  when: pre_t is defined and pre_t > 1
  
- name: Add SP sp.example.org Metadata to Shibboleth IdP
  get_url:
    url: https://sp.example.org/Shibboleth.sso/Metadata
    dest: /opt/shibboleth-idp/metadata/sp.example.org-metadata.xml
    validate_certs: no
  when: pre_t is defined and pre_t > 2 

- name: Configure SP Metadata in Shibboleth IdP
  copy:
    src: roles/shib3idp/files/metadata-providers.xml
    dest: /opt/shibboleth-idp/conf/metadata-providers.xml
  when: pre_t is defined and pre_t > 2 
  
- name: "Restart Jetty"
  become: yes
  become_method: sudo
  systemd:
   name: jetty
   daemon-reload: True
   state: restarted
  when: pre_t is defined and pre_t > 2
